version: '2.4'
services:
  dev:
    image: gfw/api-vessels
    build:
      context: .
      target: development
    env_file: ./dev/env
    command: npm start
    volumes:
      - "./src:/opt/project/src"
      - "./spec:/opt/project/spec"
      - "./package.json:/opt/project/package.json"
      - "./.eslintrc.js:/opt/project/.eslintrc.js"
      - "./dev:/opt/project/dev"
      - "cloudsql-sockets:/cloudsql"
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - NODE_ENV=development

  cloudsql:
    image: gcr.io/cloudsql-docker/gce-proxy:1.12 
    command: "/cloud_sql_proxy -instances=world-fishing-827:us-central1-a:api -credential_file=/credentials -dir=/cloudsql"
    volumes:
      - "./dev/key.json:/credentials"
      - "cloudsql-sockets:/cloudsql"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3000:8080"
    environment:
      - URL=http://localhost:8080/api

volumes:
  cloudsql-sockets:
