swagger: '2.0'
info:
  version: 1.0.0
  title: Vessels
  description: |
    The GFW Vessel API allows third parties to request aggregated information about vessels, such as identifiers, characteristics and tracks.

definitions:
  ValidationError:
    type: object
    required:
      - fields
      - general
    properties:
      fields:
        type: array
        items:
          type: object
          required:
            - field
            - errors
          properties:
            field:
              type: string
            errors:
              type: array
              items:
                type: object
                required:
                  - code
                  - description
                properties:
                  code:
                    type: string
                  description:
                    type: string
      general:
        type: array
        items:
          type: object
          required:
            - code
            - description
          properties:
            code:
              type: string
            description:
              type: string

  PaginatedVesselSearch:
    required:
      - entries
      - limit
      - nextOffset
      - offset
      - total
      - query
    properties:
      entries:
        type: array
        items:
          $ref: '#/definitions/Vessel'
      limit:
        type: number
      nextOffset:
        type: number
      offset:
        type: number
      total:
        type: number
      query:
        type: string

  VesselTypes:
    type: string
    description: |
      Specific vessel type
    enum: &VESSEL_TYPES
      - TBD

  Vessel:
    type: object
    properties:
     # New and desired properties for carrier portal
      type:
        type: string
        enum: *VESSEL_TYPES
      flag:
        description: |
          ISO code
        type: string
        minLength: 3
        maxLength: 3
      mmsi:
        type: string
      imo:
        type: array
        description: |
          History of IMOs
        items:
          type: string
      callsing:
        type: string
      authorizations:
        description: |
          History of authorizations
        type: array
        items:
          type: object
          properties:
            rfmo:
              type: string
            startDate:
              type: string
            endDate:
              type: string
      # end of new and desired properties
      end:
        type: string
      gearTypeBah:
        type: string
      gearTypeEng:
        type: string
      grossTonnage:
        type: string
      length:
        type: number
      name:
        type: string
      registeredFishingRegions:
        type: string
      registrationEndDate:
        type: string
      registrationStartDate:
        type: string
      ssvid:
        type: string
      start:
        type: string
      vesselId:
        type: string
      width:
        type: number

responses:
  PaginatedVesselSearch:
    description: |
      Response of a valid search vessel request
    schema:
      $ref: '#/definitions/PaginatedVesselSearch'

  VesselDetail:
    description: |
      Response of a valid vessel by id request
    schema:
      $ref: '#/definitions/Vessel'

  BadRequest:
    description: |
      Bad request. Invalid or wrong parameters were provided.
    schema:
      $ref: '#/definitions/ValidationError'

  Unauthorized:
    description: |
      Unauthorized, either the api key is invalid or expired.

  NotFound:
    description: |
      Not found. Either the dataset does not exist, or the specific entity
      which was requested does not exist.

paths:

  "/datasets/{dataset}/vessels":
    get:
      summary: |
        Searches for vessels
      description: |
        Searches for a vessel given a free form query. The query will be matched against any identifiers for the vessel, and a paginated, ranked results list will be returned.
      produces:
        - application/json
      parameters:
        - name: dataset
          in: path
          description: |
            Name of the dataset you want to query
          required: true
          type: string
        - name: query
          in: query
          description: |
            Search query.
          required: true
          type: string
        - name: limit
          in: query
          description: |
            Amount of search results to return. Maximum 25.
          required: false
          type: integer
          maximum: 25
          default: 10
        - name: offset
          in: query
          description: |
            Offset into the search results, used for pagination.
          required: false
          type: integer
          default: 0
      responses:
        '200':
          $ref: '#/responses/PaginatedVesselSearch'
        '401':
          $ref: '#/responses/Unauthorized'
        '400':
          $ref: '#/responses/BadRequest'

  "/datasets/{dataset}/vessels/{vesselId}":
    get:
      summary: |
        Obtains the characteristics of a single vessel
      description: |
        Obtains all the characteristics that describe a single vessel, such as its name and identifiers.
      produces:
        - application/json
      parameters:
        - name: dataset
          in: path
          description: |
            Name of the dataset you want to query
          required: true
          type: string
        - name: vesselId
          in: path
          description: |
            Id of the vessel to get the characteristics from
          required: true
          type: string
      responses:
        '200':
          $ref: '#/responses/VesselDetail'
        '401':
          $ref: '#/responses/Unauthorized'
        '400':
          $ref: '#/responses/BadRequest'

  "/datasets/{dataset}/vessels/{vesselId}":
    get:
      summary: |
        Obtains the characteristics of a single vessel
      description: |
        Obtains all the characteristics that describe a single vessel, such as its name and identifiers.
      produces:
        - application/json
      parameters:
        - name: dataset
          in: path
          description: |
            Name of the dataset you want to query
          required: true
          type: string
        - name: vesselId
          in: path
          description: |
            Id of the vessel to get the characteristics from
          required: true
          type: string
      responses:
        '200':
          description: |
            Expected resposne to a successful request.
        '401':
          $ref: '#/responses/Unauthorized'
        '400':
          $ref: '#/responses/BadRequest'

  "/datasets/{dataset}/vessels/{vesselId}/tracks":
    get:
      summary: |
        Gets the tracks of a single vessel
      description: |
        Obtains all the tracks of a single vessel.
      produces:
        - application/vnd.geo+json
      parameters:
        - name: dataset
          in: path
          description: |
            Name of the dataset you want to query
          required: true
          type: string
        - name: vesselId
          in: path
          description: |
            Id of the vessel to get the tracks for
          required: true
          type: string
        - name: features
          in: query
          description: |
            Comma-separated list of additional features to include in the
            tracks, such as points classified as fishing, per-point speed and
            courses, etc.
          type: array
          items:
            type: string
            enum:
              - fishing
              - speed
              - course
        - name: format
          in: query
          description: |
            Specific encoding format to use for the track. While the track is
            always returned as GeoJSON, you can ask for either a single
            `LineString` feature containing all the points in the track, or a
            `FeatureCollection` containing a `Point` feature for every point in
            the track.
          type: string
          enum:
            - lines
            - points
          default: lines
      responses:
        '200':
          description: |
            Expected response to a successful request.
        '401':
          $ref: '#/responses/Unauthorized'
        '400':
          $ref: '#/responses/BadRequest'
